### ISSUE TITLE
[iOS][Android][WASM][BottomBarNavigation] Sample pages do not display correctly after navigating to BottomBarNavigation 

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#99]
## Current behavior
![Uno Material broken navigation](https://user-images.githubusercontent.com/49959074/83430543-d6927100-a403-11ea-8e0a-928de662b84f.gif)

## Expected behavior

Sample should change based on what is selected from the burger menu

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Select BottomBarNavigation from burger menu
3. Select another sample from burger menu (ex. CheckBox)
4. Go back to BottomBarNavigation
5. Notice that header changes however displayed sample does not
6. Go to any sample, notice that header changes but displayed sample remains the same

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [x] UWP

## Anything else we need to know?

Unable to reproduce issue on UWP

**Comment by Massimo37** [comment]
@StewartPolsky  to be reviewed again

**Comment by Massimo37** [comment]
Fixed. @StewartPolsky to review.

**Comment by StewartPolsky** [comment]
@Massimo37 Re-opening. I was able to reproduce the issue on all platforms except WebAssembly

**Comment by StewartPolsky** [comment]
No longer able to reproduce issue on UWP. Issue still present on Android and iOS

**Comment by Massimo37** [comment]
@MatFillion  This strange error seems to be causing the issue when navigating back to the page a 2nd time:

![image](https://user-images.githubusercontent.com/36633246/84167064-bede6c80-aa43-11ea-85ad-4bd223187cb2.png)
